# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: gwas-regenie
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - regenie=1.0.6.9
  - plink2
  - r=4.0
  - r-rmarkdown=2.6
  - r-ggplot2=3.3.3
  - r-dplyr=1.0.2
  - r-dt=0.17
  - r-qqman
  - r-htmltools
  - r-rmdformats=1.0.1
  - r-skimr=2.1.3
  - r-kableextra=1.3.4
  - pandoc=2.11.3
  - cairo
  - xorg-libxt
  - fonts-anaconda=1
  - java-jdk=8.0.112
  - unzip=6.0
