name: Run Tests

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install nextflow
      run: sudo bash; mkdir /opt/nextflow; cd /opt/nextflow; wget https://github.com/nextflow-io/nextflow/releases/download/v21.04.3/nextflow; chmod +x nextflow;
    - name: Add nextflow to path
      run: echo "/opt/nextflow" >> $GITHUB_PATH;
    - name: Run CI Tests
      run:  ./run-tests.sh
      
     

